# Detect and Remove Doublets
# Creator: Dave Hill


suppressPackageStartupMessages({
  library(Seurat)
  library(DoubletFinder)
  library(parallel)
})


#' Detect and Remove Doublets with DoubletFinder
#'
#' Splits a Seurat object by sample, processes each sample independently,
#' detects doublets, removes predicted doublets, and merges the singlets.
#'
#' @param pbmc A Seurat object.
#' @param split_by Metadata column identifying separate 10X captures.
#'   Use `NULL` for a single-sample dataset.
#' @param doublet_rate Expected doublet rate as a proportion. For example,
#'   `0.075` represents 7.5 percent. This should be adjusted according to
#'   the platform and number of loaded cells.
#' @param resolution Clustering resolution used before DoubletFinder.
#' @param max_pcs Maximum number of principal components to calculate.
#' @param pN Proportion of artificial doublets generated by DoubletFinder.
#' @param seed Random seed.
#' @param cores Number of processor cores available to supported operations.
#' @param benchmark If `TRUE`, print timing and doublet summaries.
#' @param project_name Project name used when merging samples.
#'
#' @return A Seurat object containing predicted singlets. Results are stored
#'   in `pbmc@misc$benchmark$doublet_finder` and
#'   `pbmc@misc$doublet_summary`.
#'
#' @export
run_doublet_finder <- function(
    pbmc,
    split_by = "sample",
    doublet_rate = 0.075,
    resolution = 0.1,
    max_pcs = 30,
    pN = 0.25,
    seed = 8,
    cores = max(1L, parallel::detectCores() - 1L),
    benchmark = TRUE,
    project_name = "single_cell_singlets"
) {
  
  total_start <- proc.time()[["elapsed"]]
  
  # ----------------------------------------------------------------
  # 1. Validate inputs
  # ----------------------------------------------------------------
  
  validation_start <- proc.time()[["elapsed"]]
  
  pbmc$sample <- pbmc$orig.ident
  
  if (missing(pbmc) || is.null(pbmc)) {
    stop(
      "A Seurat object must be supplied as `pbmc`.",
      call. = FALSE
    )
  }
  
  if (!inherits(pbmc, "Seurat")) {
    stop(
      "`pbmc` must be a valid Seurat object.",
      call. = FALSE
    )
  }
  
  if (ncol(pbmc) < 2L) {
    stop(
      "`pbmc` must contain at least two cells.",
      call. = FALSE
    )
  }
  
  if (!is.null(split_by)) {
    if (
      !is.character(split_by) ||
      length(split_by) != 1L ||
      is.na(split_by) ||
      !nzchar(split_by)
    ) {
      stop(
        "`split_by` must be `NULL` or a single metadata column name.",
        call. = FALSE
      )
    }
    
    if (!split_by %in% colnames(pbmc@meta.data)) {
      stop(
        "The metadata column `",
        split_by,
        "` does not exist. Available columns: ",
        paste(colnames(pbmc@meta.data), collapse = ", "),
        call. = FALSE
      )
    }
    
    if (anyNA(pbmc@meta.data[[split_by]])) {
      stop(
        "The metadata column `",
        split_by,
        "` contains missing values.",
        call. = FALSE
      )
    }
  }
  
  if (
    !is.numeric(doublet_rate) ||
    length(doublet_rate) != 1L ||
    is.na(doublet_rate) ||
    !is.finite(doublet_rate) ||
    doublet_rate <= 0 ||
    doublet_rate >= 1
  ) {
    stop(
      "`doublet_rate` must be a number greater than 0 and less than 1.",
      call. = FALSE
    )
  }
  
  if (
    !is.numeric(resolution) ||
    length(resolution) != 1L ||
    is.na(resolution) ||
    !is.finite(resolution) ||
    resolution <= 0
  ) {
    stop(
      "`resolution` must be a single number greater than zero.",
      call. = FALSE
    )
  }
  
  if (
    !is.numeric(max_pcs) ||
    length(max_pcs) != 1L ||
    is.na(max_pcs) ||
    !is.finite(max_pcs) ||
    max_pcs < 2 ||
    max_pcs %% 1 != 0
  ) {
    stop(
      "`max_pcs` must be an integer of at least 2.",
      call. = FALSE
    )
  }
  
  if (
    !is.numeric(pN) ||
    length(pN) != 1L ||
    is.na(pN) ||
    !is.finite(pN) ||
    pN <= 0 ||
    pN >= 1
  ) {
    stop(
      "`pN` must be greater than 0 and less than 1.",
      call. = FALSE
    )
  }
  
  if (
    !is.numeric(seed) ||
    length(seed) != 1L ||
    is.na(seed) ||
    !is.finite(seed) ||
    seed %% 1 != 0
  ) {
    stop(
      "`seed` must be a single integer.",
      call. = FALSE
    )
  }
  
  if (
    !is.numeric(cores) ||
    length(cores) != 1L ||
    is.na(cores) ||
    !is.finite(cores) ||
    cores < 1 ||
    cores %% 1 != 0
  ) {
    stop(
      "`cores` must be an integer of at least 1.",
      call. = FALSE
    )
  }
  
  if (
    !is.logical(benchmark) ||
    length(benchmark) != 1L ||
    is.na(benchmark)
  ) {
    stop(
      "`benchmark` must be either TRUE or FALSE.",
      call. = FALSE
    )
  }
  
  validation_seconds <-
    proc.time()[["elapsed"]] - validation_start
  
  set.seed(seed)
  options(mc.cores = as.integer(cores))
  
  # ----------------------------------------------------------------
  # 2. Split the object by capture/sample
  # ----------------------------------------------------------------
  
  splitting_start <- proc.time()[["elapsed"]]
  
  if (is.null(split_by)) {
    data_split <- list(sample_1 = pbmc)
  } else {
    data_split <- Seurat::SplitObject(
      object = pbmc,
      split.by = split_by
    )
  }
  
  splitting_seconds <-
    proc.time()[["elapsed"]] - splitting_start
  
  if (length(data_split) == 0L) {
    stop(
      "Splitting the Seurat object returned no samples.",
      call. = FALSE
    )
  }
  
  sample_names <- names(data_split)
  
  if (
    is.null(sample_names) ||
    any(!nzchar(sample_names))
  ) {
    sample_names <- paste0(
      "sample_",
      seq_along(data_split)
    )
    
    names(data_split) <- sample_names
  }
  
  sample_benchmarks <- vector(
    mode = "list",
    length = length(data_split)
  )
  
  sample_summaries <- vector(
    mode = "list",
    length = length(data_split)
  )
  
  names(sample_benchmarks) <- sample_names
  names(sample_summaries) <- sample_names
  
  # ----------------------------------------------------------------
  # 3. Process every sample separately
  # ----------------------------------------------------------------
  
  for (i in seq_along(data_split)) {
    
    sample_name <- sample_names[[i]]
    sample_start <- proc.time()[["elapsed"]]
    
    message(
      "Running DoubletFinder for sample ",
      i,
      " of ",
      length(data_split),
      ": ",
      sample_name
    )
    
    data_sample <- data_split[[i]]
    cells_before <- ncol(data_sample)
    
    if (cells_before < 50L) {
      stop(
        "Sample `",
        sample_name,
        "` contains only ",
        cells_before,
        " cells. This is likely too few for reliable ",
        "DoubletFinder analysis.",
        call. = FALSE
      )
    }
    
    # --------------------------------------------------------------
    # Preprocess the sample
    # --------------------------------------------------------------
    
    preprocessing_start <- proc.time()[["elapsed"]]
    
    data_sample <- tryCatch(
      {
        data_sample <- Seurat::NormalizeData(
          data_sample,
          verbose = FALSE
        )
        
        data_sample <- Seurat::FindVariableFeatures(
          data_sample,
          selection.method = "vst",
          nfeatures = min(2000L, nrow(data_sample)),
          verbose = FALSE
        )
        
        variable_features <- Seurat::VariableFeatures(
          data_sample
        )
        
        if (length(variable_features) < 2L) {
          stop(
            "Fewer than two variable features were identified."
          )
        }
        
        data_sample <- Seurat::ScaleData(
          data_sample,
          features = variable_features,
          verbose = FALSE
        )
        
        sample_npcs <- min(
          as.integer(max_pcs),
          cells_before - 1L,
          length(variable_features) - 1L
        )
        
        if (sample_npcs < 2L) {
          stop(
            "Too few cells or variable features are available for PCA."
          )
        }
        
        data_sample <- Seurat::RunPCA(
          data_sample,
          features = variable_features,
          npcs = sample_npcs,
          seed.use = seed,
          verbose = FALSE
        )
        
        data_sample
      },
      error = function(e) {
        stop(
          "Preprocessing failed for sample `",
          sample_name,
          "`.\nOriginal error: ",
          conditionMessage(e),
          call. = FALSE
        )
      }
    )
    
    preprocessing_seconds <-
      proc.time()[["elapsed"]] - preprocessing_start
    
    # --------------------------------------------------------------
    # Select principal components
    # --------------------------------------------------------------
    
    pc_selection_start <- proc.time()[["elapsed"]]
    
    standard_deviations <- tryCatch(
      {
        Seurat::Stdev(
          data_sample,
          reduction = "pca"
        )
      },
      error = function(e) {
        stop(
          "PCA standard deviations could not be retrieved for sample `",
          sample_name,
          "`.\nOriginal error: ",
          conditionMessage(e),
          call. = FALSE
        )
      }
    )
    
    if (
      length(standard_deviations) < 2L ||
      sum(standard_deviations) <= 0
    ) {
      stop(
        "PCA produced insufficient variation for sample `",
        sample_name,
        "`.",
        call. = FALSE
      )
    }
    
    percent_stdv <-
      standard_deviations /
      sum(standard_deviations) *
      100
    
    cumulative <- cumsum(percent_stdv)
    
    cutoff_1 <- which(
      cumulative > 90 &
        percent_stdv < 5
    )[1]
    
    pc_differences <- percent_stdv[
      seq_len(length(percent_stdv) - 1L)
    ] - percent_stdv[
      2:length(percent_stdv)
    ]
    
    cutoff_candidates <- which(
      pc_differences > 0.1
    ) + 1L
    
    cutoff_2 <- if (length(cutoff_candidates) > 0L) {
      max(cutoff_candidates)
    } else {
      NA_integer_
    }
    
    available_cutoffs <- c(cutoff_1, cutoff_2)
    available_cutoffs <- available_cutoffs[
      !is.na(available_cutoffs) &
        is.finite(available_cutoffs)
    ]
    
    if (length(available_cutoffs) == 0L) {
      selected_pcs <- min(
        10L,
        length(standard_deviations)
      )
    } else {
      selected_pcs <- min(available_cutoffs)
    }
    
    # DoubletFinder requires multiple PCs
    selected_pcs <- max(
      2L,
      min(
        selected_pcs,
        length(standard_deviations)
      )
    )
    
    pcs_to_use <- seq_len(selected_pcs)
    
    pc_selection_seconds <-
      proc.time()[["elapsed"]] - pc_selection_start
    
    message(
      "Using ",
      selected_pcs,
      " principal components for ",
      sample_name,
      "."
    )
    
    # --------------------------------------------------------------
    # Finish clustering
    # --------------------------------------------------------------
    
    clustering_start <- proc.time()[["elapsed"]]
    
    data_sample <- tryCatch(
      {
        data_sample <- Seurat::RunUMAP(
          data_sample,
          dims = pcs_to_use,
          seed.use = seed,
          verbose = FALSE
        )
        
        data_sample <- Seurat::FindNeighbors(
          data_sample,
          dims = pcs_to_use,
          verbose = FALSE
        )
        
        data_sample <- Seurat::FindClusters(
          data_sample,
          resolution = resolution,
          random.seed = seed,
          verbose = FALSE
        )
        
        data_sample
      },
      error = function(e) {
        stop(
          "Clustering failed for sample `",
          sample_name,
          "`.\nOriginal error: ",
          conditionMessage(e),
          call. = FALSE
        )
      }
    )
    
    clustering_seconds <-
      proc.time()[["elapsed"]] - clustering_start
    
    # --------------------------------------------------------------
    # Find optimal pK
    # --------------------------------------------------------------
    
    parameter_sweep_start <- proc.time()[["elapsed"]]
    
    optimal_pk <- tryCatch(
      {
        sweep_list <- DoubletFinder::paramSweep(
          data_sample,
          PCs = pcs_to_use,
          sct = FALSE
        )
        
        sweep_statistics <- DoubletFinder::summarizeSweep(
          sweep_list,
          GT = FALSE
        )
        
        bcmvn <- DoubletFinder::find.pK(
          sweep_statistics
        )
        
        if (
          is.null(bcmvn) ||
          nrow(bcmvn) == 0L ||
          all(is.na(bcmvn$BCmetric))
        ) {
          stop(
            "The parameter sweep did not produce a valid BCmetric."
          )
        }
        
        selected_pk <- bcmvn$pK[
          which.max(bcmvn$BCmetric)
        ]
        
        selected_pk <- as.numeric(
          as.character(selected_pk)
        )
        
        if (
          length(selected_pk) != 1L ||
          is.na(selected_pk) ||
          !is.finite(selected_pk) ||
          selected_pk <= 0
        ) {
          stop(
            "The selected pK value is invalid."
          )
        }
        
        selected_pk
      },
      error = function(e) {
        stop(
          "DoubletFinder parameter selection failed for sample `",
          sample_name,
          "`.\nOriginal error: ",
          conditionMessage(e),
          call. = FALSE
        )
      }
    )
    
    parameter_sweep_seconds <-
      proc.time()[["elapsed"]] - parameter_sweep_start
    
    # --------------------------------------------------------------
    # Estimate the expected number of doublets
    # --------------------------------------------------------------
    
    annotations <- as.character(
      Seurat::Idents(data_sample)
    )
    
    homotypic_proportion <- tryCatch(
      {
        DoubletFinder::modelHomotypic(
          annotations
        )
      },
      error = function(e) {
        stop(
          "Homotypic doublet estimation failed for sample `",
          sample_name,
          "`.\nOriginal error: ",
          conditionMessage(e),
          call. = FALSE
        )
      }
    )
    
    expected_doublets <- max(
      1L,
      round(doublet_rate * cells_before)
    )
    
    adjusted_expected_doublets <- max(
      1L,
      round(
        expected_doublets *
          (1 - homotypic_proportion)
      )
    )
    
    # --------------------------------------------------------------
    # Run DoubletFinder
    # --------------------------------------------------------------
    
    doublet_finder_start <- proc.time()[["elapsed"]]
    
    metadata_before <- colnames(
      data_sample@meta.data
    )
    
    data_sample <- tryCatch(
      {
        DoubletFinder::doubletFinder(
          data_sample,
          PCs = pcs_to_use,
          pN = pN,
          pK = optimal_pk,
          nExp = adjusted_expected_doublets,
          reuse.pANN = NULL,
          sct = FALSE
        )
      },
      error = function(e) {
        stop(
          "DoubletFinder failed for sample `",
          sample_name,
          "`.\nOriginal error: ",
          conditionMessage(e),
          call. = FALSE
        )
      }
    )
    
    doublet_finder_seconds <-
      proc.time()[["elapsed"]] - doublet_finder_start
    
    # Locate the classification column created by DoubletFinder
    metadata_after <- colnames(
      data_sample@meta.data
    )
    
    new_columns <- setdiff(
      metadata_after,
      metadata_before
    )
    
    classification_columns <- grep(
      pattern = "^DF.classifications",
      x = new_columns,
      value = TRUE
    )
    
    if (length(classification_columns) == 0L) {
      # Fallback in case a previous column was replaced
      classification_columns <- grep(
        pattern = "^DF.classifications",
        x = metadata_after,
        value = TRUE
      )
    }
    
    if (length(classification_columns) == 0L) {
      stop(
        "DoubletFinder did not create a classification column for sample `",
        sample_name,
        "`.",
        call. = FALSE
      )
    }
    
    classification_column <- tail(
      classification_columns,
      n = 1L
    )
    
    data_sample$doublet_finder <- data_sample@meta.data[[classification_column]]
    
    doublets_detected <- sum(
      data_sample$doublet_finder == "Doublet",
      na.rm = TRUE
    )
    
    singlets_detected <- sum(
      data_sample$doublet_finder == "Singlet",
      na.rm = TRUE
    )
    
    # --------------------------------------------------------------
    # Retain singlets
    # --------------------------------------------------------------
    
    filtering_start <- proc.time()[["elapsed"]]
    
    data_singlets <- tryCatch(
      {
        subset(
          data_sample,
          subset = doublet_finder == "Singlet"
        )
      },
      error = function(e) {
        stop(
          "Singlet filtering failed for sample `",
          sample_name,
          "`.\nOriginal error: ",
          conditionMessage(e),
          call. = FALSE
        )
      }
    )
    
    filtering_seconds <-
      proc.time()[["elapsed"]] - filtering_start
    
    if (ncol(data_singlets) == 0L) {
      stop(
        "DoubletFinder removed every cell from sample `",
        sample_name,
        "`.",
        call. = FALSE
      )
    }
    
    sample_total_seconds <-
      proc.time()[["elapsed"]] - sample_start
    
    # Store the filtered sample
    data_split[[i]] <- data_singlets
    
    # Store per-sample benchmark
    sample_benchmarks[[i]] <- data.frame(
      sample = sample_name,
      step = c(
        "Preprocess sample",
        "Select principal components",
        "Cluster cells",
        "Run pK parameter sweep",
        "Run DoubletFinder",
        "Filter singlets",
        "Total sample runtime"
      ),
      elapsed_seconds = round(
        c(
          preprocessing_seconds,
          pc_selection_seconds,
          clustering_seconds,
          parameter_sweep_seconds,
          doublet_finder_seconds,
          filtering_seconds,
          sample_total_seconds
        ),
        digits = 3
      ),
      row.names = NULL
    )
    
    # Store per-sample summary
    sample_summaries[[i]] <- data.frame(
      sample = sample_name,
      cells_before = cells_before,
      expected_doublets = expected_doublets,
      adjusted_expected_doublets = adjusted_expected_doublets,
      doublets_detected = doublets_detected,
      singlets_retained = singlets_detected,
      percent_doublets = round(
        doublets_detected / cells_before * 100,
        digits = 2
      ),
      selected_pcs = selected_pcs,
      optimal_pk = optimal_pk,
      homotypic_proportion = round(
        homotypic_proportion,
        digits = 4
      ),
      row.names = NULL
    )
    
    message(
      "Completed ",
      sample_name,
      ": ",
      doublets_detected,
      " doublets removed and ",
      singlets_detected,
      " singlets retained."
    )
  }
  
  # ----------------------------------------------------------------
  # 4. Merge samples dynamically
  # ----------------------------------------------------------------
  
  merge_start <- proc.time()[["elapsed"]]
  
  if (length(data_split) == 1L) {
    
    final_singlets <- data_split[[1L]]
    
  } else {
    
    final_singlets <- tryCatch(
      {
        Seurat::merge(
          x = data_split[[1L]],
          y = unname(data_split[-1L]),
          project = project_name,
          merge.data = FALSE
        )
      },
      error = function(e) {
        stop(
          "The singlet-only sample objects could not be merged.\n",
          "Original error: ",
          conditionMessage(e),
          call. = FALSE
        )
      }
    )
  }
  
  merge_seconds <-
    proc.time()[["elapsed"]] - merge_start
  
  sample_benchmark_table <- do.call(
    rbind,
    sample_benchmarks
  )
  
  doublet_summary <- do.call(
    rbind,
    sample_summaries
  )
  
  total_seconds <-
    proc.time()[["elapsed"]] - total_start
  
  overall_benchmark <- data.frame(
    sample = "all_samples",
    step = c(
      "Validate inputs",
      "Split Seurat object",
      "Merge singlet objects",
      "Total run_doublet_finder function"
    ),
    elapsed_seconds = round(
      c(
        validation_seconds,
        splitting_seconds,
        merge_seconds,
        total_seconds
      ),
      digits = 3
    ),
    row.names = NULL
  )
  
  combined_benchmark <- rbind(
    overall_benchmark,
    sample_benchmark_table
  )
  
  # ----------------------------------------------------------------
  # 5. Store results
  # ----------------------------------------------------------------
  
  # Convert old benchmark storage into a named list
  if (is.data.frame(final_singlets@misc$benchmark)) {
    final_singlets@misc$benchmark <- list(
      previous_benchmark = final_singlets@misc$benchmark
    )
  }
  
  if (is.null(final_singlets@misc$benchmark)) {
    final_singlets@misc$benchmark <- list()
  }
  
  final_singlets@misc$benchmark[["doublet_finder"]] <-
    combined_benchmark
  
  final_singlets@misc$doublet_summary <-
    doublet_summary
  
  message(
    "\nDoubletFinder completed successfully: ",
    sum(doublet_summary$cells_before),
    " cells analyzed, ",
    sum(doublet_summary$doublets_detected),
    " doublets removed, and ",
    sum(doublet_summary$singlets_retained),
    " singlets retained."
  )
  
  if (benchmark) {
    message("\nDoublet summary:")
    print(
      doublet_summary,
      row.names = FALSE
    )
    
    message("\nDoubletFinder benchmark:")
    print(
      combined_benchmark,
      row.names = FALSE
    )
  }
  
  return(final_singlets)
}